services:
    chris1278.dsgvopermanentcheckbox.listener:
        class: chris1278\dsgvopermanentcheckbox\event\listener
        arguments:
            - '@request'
            - '@config'
            - '@template'
            - '@language'
            - '%core.php_ext%'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
